_wandb:
    value:
        cli_version: 0.22.2
        e:
            hueu8ittfu6458mu42d3ngb7aadt820w:
                codePath: main.py
                codePathLocal: main.py
                cpu_count: 40
                cpu_count_logical: 80
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "471321321472"
                        used: "330131431424"
                email: utsunomiya@mdl.cs.tsukuba.ac.jp
                executable: /home/utsu/sp_v2/.venv/bin/python
                git:
                    commit: 15d1ad77ca8dd6fa49c6eae2890811d0635f6d4c
                    remote: https://github.com/kodai-utsunomiya-mdl/spurious-feature-analysis_v2.git
                gpu: Tesla V100-SXM2-16GB
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Volta
                      cudaCores: 5120
                      memoryTotal: "17179869184"
                      name: Tesla V100-SXM2-16GB
                      uuid: GPU-291344de-fc60-b6a3-0720-452cf3268554
                host: c29e32c81b22
                memory:
                    total: "540905930752"
                os: Linux-5.4.0-193-generic-x86_64-with-glibc2.39
                program: /home/utsu/sp_v2/main.py
                python: CPython 3.12.11
                root: /home/utsu/sp_v2
                startedAt: "2025-10-28T08:47:36.208223Z"
                writerId: hueu8ittfu6458mu42d3ngb7aadt820w
        m: []
        python_version: 3.12.11
        t:
            "1":
                - 1
                - 41
            "2":
                - 1
                - 41
            "3":
                - 1
                - 13
                - 16
            "4": 3.12.11
            "5": 0.22.2
            "12": 0.22.2
            "13": linux-x86_64
activation_function:
    value: relu
analysis_target:
    value: train
analyze_gradient_basis:
    value: true
analyze_gradient_gram:
    value: false
analyze_gradient_gram_spectrum:
    value: false
analyze_gradient_norm_ratio:
    value: false
analyze_jacobian_norm:
    value: false
analyze_proposition1_terms:
    value: true
batch_size:
    value: 50000
dataset_name:
    value: WaterBirds
debias_method:
    value: SCC-GF
device:
    value: cuda
epochs:
    value: 20000
experiment_name:
    value: wb_cnn_gradient_basis
fix_final_layer:
    value: false
gradient_basis_analysis_epochs:
    value: null
gradient_gram_analysis_epochs:
    value: null
gradient_gram_spectrum_analysis_epochs:
    value: null
gradient_norm_ratio_analysis_epochs:
    value: null
gradient_norm_ratio_config:
    value:
        group_pairs:
            - - - -1
                - -1
              - - -1
                - 1
            - - - 1
                - 1
              - - 1
                - -1
initialization_method:
    value: None
jacobian_num_samples:
    value: 100
learning_rate:
    value: 0.001
loss_function:
    value: mse
momentum:
    value: 0.9
num_test_samples:
    value: 9000
num_train_samples:
    value: 50000
optimizer:
    value: SGD
proposition1_terms:
    value:
        group_pairs:
            - - - -1
                - 1
              - - -1
                - -1
            - - - 1
                - -1
              - - 1
                - 1
proposition1_terms_analysis_epochs:
    value: null
scc_micro_batch_size:
    value: 64
show_and_save_samples:
    value: true
test_attribute_marginal:
    value: 0
test_correlation:
    value: 0
test_label_marginal:
    value: 0
train_attribute_marginal:
    value: 0
train_correlation:
    value: 0.8
train_label_marginal:
    value: 0
use_skip_connections:
    value: false
wandb:
    value:
        enable: true
        entity: mdl-tsukuba
        project: sp_exp_gram_basis
